version: '3.1'
services:
    mongodb:
        image: mongo:latest
        container_name: "slrt_mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./data/db:/data/db
        expose:
            - 27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet
    backend:
        links:
            - mongodb:mongodb
    webapp:
        links:
            - backend:backend
