version: '3.1'
services:
    backend:
        # container_name: "sl_backend_development"
        build:
            context: ./backend
            dockerfile: Dockerfile.production
        image: slrt_api_prod
        ports:
            - 8011:3000
        environment:
            NODE_ENV: production
    webapp:
        # container_name: "sl_backend_development"
        build:
            context: ./webapp
            dockerfile: Dockerfile.production
        image: slrt_webapp_prod
        ports:
            - 8010:80
        environment:
            NODE_ENV: production
